#!/bin/bash

# Bash Variables.
# https://www.gnu.org/software/bash/manual/html_node/Bash-Variables.html

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Make `vim` the default editor.

export EDITOR="vim"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Ignore commands that start with spaces and duplicates.

# export HISTCONTROL=ignoreboth

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Increase the maximum number of lines of history
# persisted in the history file (default value is 500).

# export HISTFILESIZE=10000

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Don't add certain commands to the history file.

# export HISTIGNORE="&:[bf]g:c:clear:history:exit:q:pwd:* --help"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Increase the maximum number of commands recorded
# in the command history (default value is 500).

# export HISTSIZE=10000

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Prefer US English and use UTF-8 encoding.

export LANG="en_US.UTF-8"
export LC_ALL="en_US.UTF-8"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Use custom `less` colors for `man` pages.

# export LESS_TERMCAP_md="$(tput bold 2> /dev/null; tput setaf 2 2> /dev/null)"
# export LESS_TERMCAP_me="$(tput sgr0 2> /dev/null)"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Don't clear the screen after quitting a `man` page.

export MANPAGER="less -X"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Increase the maximum number of lines of history persisted
# in the `Node` REPL history file (default value is 1000).
#
# https://github.com/nodejs/node/blob/c948877688ff2b6a37f2c88724b656aae495c7b2/doc/api/repl.md#persistent-history

# export NODE_REPL_HISTORY_SIZE=10000

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Make new shells get the history lines from all previous
# shells instead of the default "last window closed" history.

# export PROMPT_COMMAND="history -a; $PROMPT_COMMAND"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Make Python use UTF-8 encoding for output to stdin/stdout/stderr.

export PYTHONIOENCODING="UTF-8"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Add rbenv as to path as a function (may not need, need to test installing again using brew.)
# add_to_path_end "$HOME/.rbenv/bin"
export PATH="$HOME/.rbenv/bin:$PATH"
if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# set homebrew path (not sure if needed, try installing brew again.)
# homebrew=/usr/local/bin:/usr/local/sbin
# add_to_path "$homebrew"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# java 8 home for building android
if [ "$(uname -s)" = "Darwin" ]; then
  # unset first as Big Sur set default that we don't want
  # https://developer.apple.com/forums/thread/666681
  unset JAVA_HOME
  java8_path="$(/usr/libexec/java_home -v "1.8.0")"
  export JAVA_HOME=$java8_path
  export STUDIO_JDK=$java8_path
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# android home
if [ "$(uname -s)" = "Darwin" ]; then
  export ANDROID_SDK_ROOT="$HOME/Library/Android/sdk"
  export ANDROID_HOME="$HOME/Library/Android/sdk"

  export PATH="$ANDROID_HOME/tools:$PATH"
  export PATH="$ANDROID_HOME/platform-tools:$PATH"
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Add miniconda to path (may not need, need to test installing miniconda using brew cask first.)
# export PATH="/Users/tulakan/miniconda3/bin:$PATH"
if [ "$(uname -s)" = "Darwin" ]; then
  export PATH="/usr/local/miniconda3/bin":$PATH
else
  export PATH="$HOME/miniconda3/bin":$PATH
fi

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# Add dotnet path manually as there is conflict problem with oh-my-zsh
# https://github.com/dotnet/cli/issues/1567
# export PATH=$PATH:"/usr/local/share/dotnet"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# nvm
# thanks to:
# https://medium.com/@dannysmith/little-thing-2-speeding-up-zsh-f1860390f92
# https://www.reddit.com/r/node/comments/4tg5jg/lazy_load_nvm_for_faster_shell_start/d5ib9fs/?context=3
declare -a NODE_GLOBALS=(`find ~/.nvm/versions/node -maxdepth 3 -type l -wholename '*/bin/*' | xargs -n1 basename | sort | uniq`)

NODE_GLOBALS+=("node")
NODE_GLOBALS+=("nvm")

load_nvm () {
  echo "🚨 NVM not loaded! Loading now..."
  export NVM_DIR="$HOME/.nvm"
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
}

for cmd in "${NODE_GLOBALS[@]}"; do
  eval "${cmd}(){ unset -f ${NODE_GLOBALS}; load_nvm; nvm use || nvm use default; ${cmd} \$@ }"
done

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

# z
. /usr/local/etc/profile.d/z.sh
